# Generated by Django 5.1.1 on 2024-10-03 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoiBong',
            fields=[
                ('ma_doi_bong', models.AutoField(primary_key=True, serialize=False)),
                ('ten', models.CharField(max_length=100)),
                ('san_van_dong', models.CharField(max_length=100)),
                ('nam_thanh_lap', models.IntegerField()),
            ],
            options={
                'db_table': 'DoiBong',
            },
        ),
        migrations.CreateModel(
            name='ThanhTichDoiBong',
            fields=[
                ('ma_thanh_tich', models.AutoField(primary_key=True, serialize=False)),
                ('ten_thanh_tich', models.CharField(max_length=255)),
                ('nam_thanh_tich', models.IntegerField()),
                ('mo_ta', models.TextField()),
                ('doi_bong_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doibong')),
            ],
            options={
                'db_table': 'ThanhTichDoiBong',
            },
        ),
    ]
