# Generated by Django 5.1.1 on 2024-10-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cauthu_huanluyenvien_hopdong_kinhnghiemhuanluyen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thanhtichdoibong',
            old_name='doi_bong_id',
            new_name='doi_bong',
        ),
        migrations.RenameField(
            model_name='thanhtichdoibong',
            old_name='nam_thanh_tich',
            new_name='nam',
        ),
        migrations.AlterField(
            model_name='thanhtichdoibong',
            name='mo_ta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
