# Generated by Django 5.1.1 on 2024-10-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_doi_bong_id_thanhtichdoibong_doi_bong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doibong',
            name='logo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
