# Generated by Django 5.1.1 on 2024-10-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_doibong_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cauthu',
            name='hinh_anh',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='huanluyenvien',
            name='hinh_anh',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
